In [113]:
import open3d as o3d
import os
# !pip install trimesh
import trimesh
from plyfile import PlyData, PlyElement

In [15]:
files = [_ for _ in  os.listdir("./") if "glb" in _]

In [70]:
for idx,path_obj in enumerate(files):
    mesh = o3d.io.read_triangle_mesh(path_obj)
    mesh.compute_vertex_normals()
    pcd = mesh.sample_points_uniformly(number_of_points=8192)
    # o3d.visualization.draw_geometries([mesh])
    m = trimesh.load(path_obj, force='mesh')
    point_positions = np.array(pcd.points)
    point_colors = (np.random.random(size=[8192, 3]) * 255).astype(np.uint8)
    np.save(path_obj[:-4]+"_8192.npy",point_positions)
    # v.add_points("try_"+str(idx), point_positions, point_colors, point_size=25.0)

In [104]:
mesh = trimesh.load("00014d97ce5247deb063e4e245994b72.glb",force='mesh')
mesh

<trimesh.Trimesh(vertices.shape=(32870, 3), faces.shape=(16935, 3))>

In [84]:
mesh

<trimesh.Scene(len(geometry)=14, name=`00014d97ce5247deb063e4e245994b72.glb`)>

In [81]:
mesh.TriangleMesh

<Type.TriangleMesh: 6>

In [52]:
import pyviz3d.visualizer as viz
import numpy as np

In [60]:
v = viz.Visualizer()
point_positions = np.array(pcd.points)
point_colors = (np.random.random(size=[8192, 3]) * 255).astype(np.uint8)
v.add_points("try", point_positions, point_colors, point_size=25.0)

In [64]:
v.save("./try")


************************************************************************
1) Start local server:
    cd /home/linfeng/PointLLM/data/try; python -m http.server 6008
2) Open in browser:
    http://0.0.0.0:6008
************************************************************************


In [106]:
files = os.listdir("/data2/llf/ShapeNet/02691156")

In [114]:
for i in files:
    # a = np.load(os.path.join("/data2","llf","ShapeNet","02691156",i),allow_pickle=True)
    x = PlyData.read(os.path.join("/data2","llf","ShapeNet","02691156",i))
    break

In [1]:
import numpy as np

In [4]:
a = np.load("/data2/llf/fss_data/ScanNet/scenes/data/scene0000_00.npy")

In [6]:
a[0]

array([ 3.8378706 ,  8.08761024,  1.85999155, 85.        , 75.        ,
       57.        , 15.        ])

In [11]:
b = np.load("/data2/llf/fss_data/ScanNet/scene0000_00_block_2.npy")

In [17]:
b = b[:,0:6]

In [19]:
b[0]

array([ 0.44704896,  5.01072542,  1.29732772, 63.        , 51.        ,
       40.        ])

In [23]:
b[:,3:] = b[:,3:]/255

In [24]:
b

array([[0.44704896, 5.01072542, 1.29732772, 0.24705882, 0.2       ,
        0.15686275],
       [0.4256868 , 5.02555506, 1.31904682, 0.44313725, 0.4       ,
        0.28235294],
       [0.40879276, 5.03898041, 1.47939226, 0.43137255, 0.27843137,
        0.14117647],
       ...,
       [0.64455345, 5.00621359, 0.59368434, 0.2       , 0.15294118,
        0.08627451],
       [0.55486849, 5.06028406, 0.57758125, 0.30980392, 0.24705882,
        0.16862745],
       [0.62935128, 5.0486912 , 0.58648058, 0.16862745, 0.14901961,
        0.09019608]])